### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas' 

### ISSUE THREAD

**Issue by juhele** [JakubBrom/RadAgro#1]
In linux (Kubuntu 20.04) you need to have package "python3-pandas" installed. Otherwise you get error:

```
Nemohu načíst zásuvný modul 'RadAgro-master' kvůli chybě při volání metody classFactory() 

ModuleNotFoundError: No module named 'pandas' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/jan_helebrant/.local/share/QGIS/QGIS3/profiles/default/python/plugins/RadAgro-master/__init__.py", line 35, in classFactory
    from .RadAgro import RadAgro
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jan_helebrant/.local/share/QGIS/QGIS3/profiles/default/python/plugins/RadAgro-master/RadAgro.py", line 51, in 
    import pandas as pd
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pandas'


Verze Pythonu: 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0] 
QGIS verze: 3.20.0-Odense Odense, decaadbb31 

Python cesta:
/home/jan_helebrant/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-safecast-plugin-master/layer/..
/usr/share/qgis/python
/home/jan_helebrant/.local/share/QGIS/QGIS3/profiles/default/python
/home/jan_helebrant/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/jan_helebrant/.local/share/QGIS/QGIS3/profiles/default/python
```
I would recommend to add this in plugin description or readme here to prevent new users having this issue. :-)

thanks

**Comment by JakubBrom** [comment]
Fixed
